# Generated by Django 5.0.3 on 2024-03-12 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="mailing_list",
            new_name="mailing_event",
        ),
    ]
