# Generated by Django 4.2.11 on 2024-03-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingevent",
            name="clients",
            field=models.ManyToManyField(
                related_name="mailing_events",
                to="distribution.client",
                verbose_name="клиенты",
            ),
        ),
    ]
