# Generated by Django 4.2.11 on 2024-04-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingevent',
            options={'permissions': [('set_is_active', 'Установка активации рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
