# Generated by Django 4.2.11 on 2024-04-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_alter_mailingevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingevent',
            options={'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
