# Generated by Django 4.2.11 on 2024-03-23 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0003_mailingevent_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="mailing_event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="distribution.mailingevent",
                verbose_name="рассылка",
            ),
        ),
    ]
