# Generated by Django 4.2.11 on 2024-03-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0004_alter_message_mailing_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingevent",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активация рассылки"),
        ),
    ]
